const express = require('express');
const cors = require('cors');
const path = require('path');
const ExcelJS = require('exceljs');

const app = express();
const PORT = process.env.PORT || 3000;

/* ================= MIDDLEWARE ================= */
app.use(cors());
app.use(express.json());

/* ================= FRONTEND ================= */
app.use(express.static(path.join(__dirname, 'public')));

// GARANTE "/" NO RENDER
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
    });

    /* ================= BANCO EM MEMÓRIA ================= */
    let database = [];

    /* ================= FUNÇÕES ================= */
    function extrair(payload, campo) {
        if (typeof payload !== 'string') return '';
            const p = payload.split('&').find(x => x.startsWith(campo + '='));
                return p ? decodeURIComponent(p.split('=')[1] || '') : '';
                }

                /* ================= API ================= */

                // RECEBE AÇÕES DO TAMPERMONKEY
                app.post('/api/acao', (req, res) => {
                    const registro = {
                            mesa: req.body.mesa || 'DESCONHECIDA',
                                    tipo: req.body.tipo || 'LANÇAMENTO',
                                            payload: req.body.payload || '',
                                                    timestamp: req.body.timestamp || new Date().toISOString()
                                                        };

                                                            database.unshift(registro);
                                                                if (database.length > 300) database.pop();

                                                                    res.json({ ok: true });
                                                                    });

                                                                    // HISTÓRICO COMPLETO
                                                                    app.get('/api/historico', (req, res) => {
                                                                        res.json(database);
                                                                        });

                                                                        // FINANCEIRO
                                                                        app.get('/api/financeiro', (req, res) => {
                                                                            let total = 0;

                                                                                database.forEach(d => {
                                                                                        if (d.tipo === 'LANÇAMENTO') {
                                                                                                    const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                                                                const valor = Number(
                                                                                                                                extrair(d.payload, 'valor_unitario')
                                                                                                                                                    .replace('.', '')
                                                                                                                                                                        .replace(',', '.')
                                                                                                                                                                                    ) || 0;

                                                                                                                                                                                                total += qtde * valor;
                                                                                                                                                                                                        }
                                                                                                                                                                                                            });

                                                                                                                                                                                                                res.json({
                                                                                                                                                                                                                        total,
                                                                                                                                                                                                                                comissao: total * 0.06 + 140,
                                                                                                                                                                                                                                        taxa: total * 0.04
                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                            // RANKING POR MESA
                                                                                                                                                                                                                                            app.get('/api/ranking', (req, res) => {
                                                                                                                                                                                                                                                const ranking = {};

                                                                                                                                                                                                                                                    database.forEach(d => {
                                                                                                                                                                                                                                                            if (d.tipo === 'LANÇAMENTO') {
                                                                                                                                                                                                                                                                        const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                                                                                                                                                                                                                                    const valor = Number(
                                                                                                                                                                                                                                                                                                    extrair(d.payload, 'valor_unitario')
                                                                                                                                                                                                                                                                                                                        .replace('.', '')
                                                                                                                                                                                                                                                                                                                                            .replace(',', '.')
                                                                                                                                                                                                                                                                                                                                                        ) || 0;

                                                                                                                                                                                                                                                                                                                                                                    ranking[d.mesa] = (ranking[d.mesa] || 0) + qtde * valor;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                    res.json(
                                                                                                                                                                                                                                                                                                                                                                                            Object.entries(ranking)
                                                                                                                                                                                                                                                                                                                                                                                                        .map(([mesa, total]) => ({ mesa, total }))
                                                                                                                                                                                                                                                                                                                                                                                                                    .sort((a, b) => b.total - a.total)
                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                        // EXPORTAÇÃO EXCEL COMPLETA
                                                                                                                                                                                                                                                                                                                                                                                                                        app.get('/api/export/excel', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                            const wb = new ExcelJS.Workbook();

                                                                                                                                                                                                                                                                                                                                                                                                                                /* ===== LANÇAMENTOS ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                    const wsLanc = wb.addWorksheet('LANÇAMENTOS');
                                                                                                                                                                                                                                                                                                                                                                                                                                        wsLanc.columns = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Mesa', key: 'mesa', width: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Produto', key: 'produto', width: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Quantidade', key: 'qtde', width: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Valor Unitário', key: 'valor', width: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Total', key: 'total', width: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Horário', key: 'hora', width: 22 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let totalGeral = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ranking = {};

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        database
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .filter(d => d.tipo === 'LANÇAMENTO')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .forEach(d => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const produto = extrair(d.payload, 'nome_item');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const valor = Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            extrair(d.payload, 'valor_unitario')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .replace('.', '')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .replace(',', '.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) || 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const total = qtde * valor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalGeral += total;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ranking[d.mesa] = (ranking[d.mesa] || 0) + total;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wsLanc.addRow({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mesa: d.mesa,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                produto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                qtde,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                valor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hora: new Date(d.timestamp).toLocaleString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ===== RANKING ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const wsRank = wb.addWorksheet('RANKING');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wsRank.columns = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Mesa', key: 'mesa', width: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Total', key: 'total', width: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Object.entries(ranking)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .sort((a, b) => b[1] - a[1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .forEach(([mesa, total]) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wsRank.addRow({ mesa, total })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /* ===== GERAL ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const wsGeral = wb.addWorksheet('GERAL');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        wsGeral.addRow(['Valor Total', totalGeral]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            wsGeral.addRow(['Comissão 6%', totalGeral * 0.06 + 140]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wsGeral.addRow(['Taxa 4%', totalGeral * 0.04]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.setHeader(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.setHeader(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Disposition',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'attachment; filename=relatorio_lechef.xlsx'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await wb.xlsx.write(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ================= START ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('LeChef Monitor ativo na porta', PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }); de