const express = require('express');
const cors = require('cors');
const path = require('path');
const ExcelJS = require('exceljs');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

let database = [];

/* ===== UTIL ===== */
function extrair(payload, campo) {
    if (typeof payload !== 'string') return '';
        const p = payload.split('&').find(x => x.startsWith(campo + '='));
            return p ? decodeURIComponent(p.split('=')[1] || '') : '';
            }

            /* ===== RECEBE ===== */
            app.post('/api/acao', (req, res) => {
                database.unshift(req.body);
                    if (database.length > 200) database.pop();
                        res.json({ ok: true });
                        });

                        /* ===== HISTÓRICO ===== */
                        app.get('/api/historico', (req, res) => {
                            res.json(database);
                            });

                            /* ===== FINANCEIRO ===== */
                            app.get('/api/financeiro', (req, res) => {
                                let total = 0;

                                    database.forEach(d => {
                                            if (d.tipo === 'LANÇAMENTO') {
                                                        const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                    const valor = Number(
                                                                                    extrair(d.payload, 'valor_unitario')
                                                                                                        .replace('.', '')
                                                                                                                            .replace(',', '.')
                                                                                                                                        ) || 0;
                                                                                                                                                    total += qtde * valor;
                                                                                                                                                            }
                                                                                                                                                                });

                                                                                                                                                                    res.json({
                                                                                                                                                                            total,
                                                                                                                                                                                    comissao: total * 0.06 + 140,
                                                                                                                                                                                            taxa: total * 0.04
                                                                                                                                                                                                });
                                                                                                                                                                                                });

                                                                                                                                                                                                /* ===== RANKING ===== */
                                                                                                                                                                                                app.get('/api/ranking', (req, res) => {
                                                                                                                                                                                                    const r = {};
                                                                                                                                                                                                        database.forEach(d => {
                                                                                                                                                                                                                if (d.tipo === 'LANÇAMENTO') {
                                                                                                                                                                                                                            const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                                                                                                                                                                                        const valor = Number(
                                                                                                                                                                                                                                                        extrair(d.payload, 'valor_unitario')
                                                                                                                                                                                                                                                                            .replace('.', '')
                                                                                                                                                                                                                                                                                                .replace(',', '.')
                                                                                                                                                                                                                                                                                                            ) || 0;
                                                                                                                                                                                                                                                                                                                        r[d.mesa] = (r[d.mesa] || 0) + qtde * valor;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                        res.json(
                                                                                                                                                                                                                                                                                                                                                Object.entries(r)
                                                                                                                                                                                                                                                                                                                                                            .map(([mesa, total]) => ({ mesa, total }))
                                                                                                                                                                                                                                                                                                                                                                        .sort((a, b) => b.total - a.total)
                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                            /* ===== EXPORT EXCEL ===== */
                                                                                                                                                                                                                                                                                                                                                                            app.get('/api/export/excel', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                const wb = new ExcelJS.Workbook();

                                                                                                                                                                                                                                                                                                                                                                                    const wsL = wb.addWorksheet('LANÇAMENTOS');
                                                                                                                                                                                                                                                                                                                                                                                        wsL.columns = [
                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Mesa', key: 'mesa', width: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Produto', key: 'produto', width: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Qtde', key: 'qtde', width: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Valor Unitário', key: 'valor', width: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Total', key: 'total', width: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Hora', key: 'hora', width: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                let totalGeral = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ranking = {};

                                                                                                                                                                                                                                                                                                                                                                                                                                                        database.filter(d => d.tipo === 'LANÇAMENTO').forEach(d => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const produto = extrair(d.payload, 'nome_item');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const qtde = Number(extrair(d.payload, 'quantidade')) || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const valor = Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            extrair(d.payload, 'valor_unitario')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .replace('.', '')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .replace(',', '.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const total = qtde * valor;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    totalGeral += total;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ranking[d.mesa] = (ranking[d.mesa] || 0) + total;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wsL.addRow({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mesa: d.mesa,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            produto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        qtde,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    valor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            hora: new Date(d.timestamp).toLocaleString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const wsR = wb.addWorksheet('RANKING');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wsR.columns = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { header: 'Mesa', key: 'mesa', width: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { header: 'Total', key: 'total', width: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Object.entries(ranking)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .sort((a, b) => b[1] - a[1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .forEach(([mesa, total]) => wsR.addRow({ mesa, total }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const wsG = wb.addWorksheet('GERAL');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wsG.addRow(['Valor Total', totalGeral]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wsG.addRow(['Comissão 6%', totalGeral * 0.06 + 140]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        wsG.addRow(['Taxa 4%', totalGeral * 0.04]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.setHeader(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.setHeader(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Disposition',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'attachment; filename=lechef_relatorio.xlsx'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await wb.xlsx.write(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.listen(PORT, () => console.log('Servidor ativo na porta', PORT));